language: python
python:
  - "2.7"
install:
  - pip install -q sphinx
  - pip install -r requirements.txt
script: sphinx-build -nW -b html -d _build/doctrees . _build/html

# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
